export const NUM_RESULTS_PER_PAGE = 6
export const AUDIO_LIST_KEY = "AUDIO"
export const DEFAULT_SERVER_URL = "http://vpn.desktop.travistang.rocks:3005"
export const SERVER_URL_KEY = '@SERVER_URL'

export const SERVER_TO_DEVICE_STATUS = {
  DOWNLOADING_TO_DEVICE : "DOWNLOADING_TO_DEVICE",
  DOWNLOADING_TO_DEVICE_FAILED : "DOWNLOADING_TO_DEVICE_FAILED",
  DOWNLOADED : "DOWNLOADED"
}
